name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: +release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: +release
        run: earthly --secret GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --ci --use-inline-cache --push +release

  docker:
    name: +docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: +docker
        run: earthly --secret GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --use-inline-cache --push +docker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - run: docker tag tempura:latest ghcr.io/korosuke613/tempura:${GITHUB_REF##*/}
      - run: docker push ghcr.io/korosuke613/tempura:${GITHUB_REF##*/}
